export default {
    all: "All",
    featuredHeadlines: "Featured Headlines",
    news: "News",
    sports: "Sports",
    opinions: "Opinions",
    arts: "Arts & Life",
    grind: "The Grind",
    humor: "Humor",
    data: "Data",
    headlines: "headlines",
    placeholder: "placeholder",
    post: "Post",
    posts: "posts",
    category: "Category",
    hashed: "hashed",
    requestSmallPage: "https://www.stanforddaily.com/wp-json/wp/v2/posts/?_embed&per_page=3&page=",
    requestLargePage: "https://www.stanforddaily.com/wp-json/wp/v2/posts/?_embed&per_page=10&page=",
    searchURL: "&search=",
    categoriesURL: "&categories=",
    categoryChanged: "Category Changed",
    page: "page",
    static: "static",
    lightContent: "light-content",
    moreText: "...",
    mediaURL: 'https://www.stanforddaily.com/wp-json/wp/v2/media/',
    dailyURL: 'https://www.stanforddaily.com/',
    profile: "Profile",
    childRemoved: "child_removed",
    replies: "replies",
    repliesBodies: "repliesBodies",
    repliesCount: "repliesCount",
    no: "no",
    yes: "yes",
    anon: "Anonymous",
    val: "value",
    timestamp: "TimeStamp",
    chatterPostSuffix: "'s post",
    detailedPost: "DetailedPost",
    pad: "padding",
    replyPlaceholder: "Write a reply...",
    img: "image",
    appOpened: "App opened",
    articlesPreviewRequest: "Article preview request",
    articleFullLoaded: "Article Clicked",
    none: "none",
    undefined: "undefined",
    newestToOldest: "sortDate",
    postsBodies: "postsBodies",
    author: "Author",
    authors: "Authors",
    chatter: "Chatter",
    signedIn: "signedIn",
    users: "Users",
    verified: "verified",
    list: "list",
    profilePictures: "profile_pictures",
    switchedScreen: "Switched Screen",
    loadChatterPosts: "Request for more chatter posts",
    voteChanged: "New vote",
    newReply: "New Reply",
    up: "up",
    down: "down",
    bold: "bold",
    votes: "votes",
    voters: "voters",
    publicPosts: "publicPosts",
    name: "name",
    search: "Search",
    reply: "Reply",
    tipsFormURL: "https://docs.google.com/forms/d/e/1FAIpQLSfrUp-7TeCqe_Whw9LRCttG2It3unK8rJfxNLu9IXZdcbeDIA/viewform?embedded=true",
    tipsFormURLPrefix: "https://docs.google.com/forms/d/e/1FAIpQLSfrUp-7TeCqe_Whw9LRCttG2It3unK8rJfxNLu9IXZdcbeDIA",
    wordPressURL: "https://stanforddaily.com",
}