export { default as Author } from "./Author"
export { default as Home } from "./Home"
export { default as Post } from "./Post"
export { default as Search } from "./Search"
export { default as Section } from "./Section"