# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StanfordDaily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StanfordDaily
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'StanfordDailyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
  end

end

target 'StanfordDaily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StanfordDaily-tvOS

  target 'StanfordDaily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
