# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StanfordDaily' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StanfordDaily
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Firebase'
  pod 'Amplitude-iOS'

  target 'StanfordDailyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'Firebase'
    pod 'Amplitude-iOS'
  end

end

target 'StanfordDaily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StanfordDaily-tvOS

  target 'StanfordDaily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
